shot_numbers: 31779
trees: KSTAR # Common tree to all pointnames listed below
point_names:
  - EP53:FOO # Note that \ is not required.
  - EP54:FOO
  - EP47:FOO
  - EP57:FOO
host: omega.gat.com
resample: [-0.1, 20, 0.1] # Optional but reduces the amount of data handled
out_filename: test.h5
server: 203.230.126.231:8005
verbose: true
