shot_numbers: 31779
trees: KSTAR
point_names:
  - EP53:FOO # Note that \ is not required.
  - EP54:FOO
  - EP47:FOO
  - EP57:FOO
host: iris.gat.com
resample: [-0.1, 20, 0.1]
out_filename: test.h5
server: 203.230.126.231:8005
verbose: true
